### PR TITLE
Updates for ionic-angular 2.0.0-rc.1

### PR DESCRIPTION
**Pull request by SteveKennedy**
These changes may help contribute toward bringing this template to support ionic 2 RC1  (ionic-angular 2.0.0-rc.1).

### CODE REVIEW

**Comment by jmatthiesen** [comment]
Thanks for the pull request! To handle the npm scripts with Task Runner Explorer, are you using a 3rd party extension right now? If so, which one? I'm thinking we'll need to add some extra instructions to the readme to handle this.

**Comment by SteveKennedy** [comment]
@jmatthiesen Done. Thoughts?  (It was NPM Task Runner - https://visualstudiogallery.msdn.microsoft.com/8f2f2cbc-4da5-43ba-9de2-c9d08ade4941)

**Comment by SimoneBerardi** [comment]
Good morning,
i'm starting a new project for an hybrid app and was trying to get ionic v2 rc up and running on Visual Studio. I want to point out that i'm new to angular 2 but i also used quite extensively the ionic v1 project templates for Visual Studio and got some working apps out of them.

I made a clone of this pull request and tried to follow the advanced angular 2 tutorial (https://angular.io/docs/ts/latest/tutorial/) up to part 6 and i'm facing quite an handfull of problems:
- the intellisense won't find Promise definition even though the project compiles it and works at runtime;
- i'm not able to debug ts files from Visual Studio (they wont appear under the source files) even if the task runner is generating the main.js.map and i can debug those files on chrome inspect page
- using the routing module of angular 2 i would like to assign the moduleId to module.id into the component definition but this operation fails to compile since module seems to not be defined.

I would really appreciate any help that can be given about this situation since i would love to start working onto ionic-angular 2 rc1 as soon as possible due to time constraints.
Would also be nice to hear if there is any ETA of the official release on this matter.

Thanks for your time and attention.

**Comment by bowdenk7** [comment]
Hi @SimoneBerardi, do you have this file in your project?
`node_modules/@types/core-js/index.d.ts`

**Comment by SimoneBerardi** [comment]
Hey there @bowdenk7 , no i don't have it in my project. Is it supposed to be there already within the package.json dependencies or is it included by other means?

**Pull request merged**
